### ISSUE TITLE
Load solar wind speeds from spacecraft

### ISSUE THREAD

**Issue by johan12345** [johan12345/heliospheric_propagation_tool#1]
e.g. ACE https://docs.heliopy.org/en/stable/api/heliopy.data.ace.swe_h2.html#heliopy.data.ace.swe_h2

STEREO not yet implemented: https://github.com/heliopython/heliopy/pull/851

**Comment by dstansby** [comment]
As a heads up I'm adding STEREO now: https://github.com/heliopython/heliopy/pull/923 - if there's any specific data products you are after then please open an issue on the heliopy repo!

**Comment by johan12345** [comment]
This repository has moved to https://github.com/esdc-esac-esa-int/Solar-MACH
see: https://github.com/esdc-esac-esa-int/Solar-MACH/issues/1
